apiVersion: v1
kind: Service
metadata:
  name: database-admin-service
spec:
  type: NodePort
  selector:
    app: database_admin
  ports:
    - protocol: TCP
      port: 80               # Internal service port for database admin interface
      targetPort: 80          # Container's port for admin access
      nodePort: 30082         # Exposed on the node for external access

