apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432             # Internal PostgreSQL port
      targetPort: 5432        # Container's PostgreSQL port
      nodePort: 30081         # Exposed on the node for database access

