apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 5432  # The PostgresSQL service runs on port 80 inside the container

