apiVersion: v1
kind: Service
metadata:
  name: directory-admin-service
spec:
  type: NodePort
  selector:
    app: directory_admin
  ports:
    - protocol: TCP
      port: 80               # Internal service port for LDAP admin interface
      targetPort: 80          # Container's port for admin access
      nodePort: 30083         # Exposed on the node for external access

