apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: {{IMAGE_NAME}}
        ports:
        - containerPort: 80  # The web service runs on port 80 inside the container
        - containerPort: 443  # The web service runs on port 443 inside the container

