apiVersion: v1
kind: Service
metadata:
  name: www-service
spec:
  type: NodePort  # Expose the service using NodePort
  selector:
    app: www
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8888
      targetPort: 80
      name: stackhawk-scan
    - port: 443
      targetPort: 443
      name: https
